# Database

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Application URL

app.base-url=${APP_BASE_URL}

# Docker Compose

spring.docker.compose.enabled=false